require: rubocop-jekyll
inherit_gem:
  rubocop-jekyll: .rubocop.yml

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Metrics/ParameterLists:
  Max: 6

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '[]'
    '%I': '[]'
    '%r': '{}'
    '%w': '[]'
    '%W': '[]'

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Layout/LineLength:
  Max: 120

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

AllCops:
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'
