# Site settings
title: Alfredo Ramos
description: 'Personal GitHub page'
#baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://alfredoramos.github.io' # the base hostname & protocol for your site
social_networks: {
    github: {
        user: 'AlfredoRamos',
        url: 'https://github.com/AlfredoRamos',
    },
    twitter: {
        user: 'AbaddonOrmuz',
        url: 'https://twitter.com/AbaddonOrmuz'
    },
    reddit: {
        user: 'AbaddonOrmuz',
        url: 'https://reddit.com/u/AbaddonOrmuz'
    }
}

# Build settings
markdown: kramdown

encoding: 'utf-8'
permalink: 'none'
timezone: America/Mexico_City
exclude: [LICENSE, Rakefile]
