# Site settings
title: 'Alfredo Ramos'
description: null
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://alfredoramos.mx' # the base hostname & protocol for your site
discourse_url: 'https://dev.alfredoramos.mx/'

# Default settings
defaults:
  -
    scope:
      path: '' # all files
      type: drafts
    values:
      layout: post
      author: AlfredoRamos
      permalink: /:title
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      author: AlfredoRamos
      permalink: /:title
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
      author: AlfredoRamos

# Build settings
theme: null
encoding: 'utf-8'
pagination:
  enabled: true
  title: ':title'
  per_page: 12
  permalink: '/page/:num/'
  sort_reverse: true
timezone: America/Mexico_City
exclude:
  - dist/
  - CNAME
  - LICENSE
  - Rakefile
  - README.md
  - composer.json
  - composer.lock
  - satis.json
  - vendor
  - Gemfile
  - Gemfile.lock
kramdown:
    input: GFM
    hard_wrap: false
sass:
    sass_dir: _scss
    style: compressed
plugins:
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-target-blank
excerpt_separator: <!-- more -->

verifications:
    google: 'sgG6KmCJADN3NqJaCyaVjnhYBciwR2LM2uz8rgdGTJU'
    yandex: '9342b30f7f9146b5'

word_per_minute: 180 # WPM
image_view_time: 3   # Seconds

target-blank:
    rel: external

repository: AlfredoRamos/AlfredoRamos.github.io
