# Site settings
title: 'Alfredo Ramos'
description: 'Personal GitHub page'
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://alfredoramos.github.io' # the base hostname & protocol for your site

# Default settings
defaults:
  -
    scope:
      path: '' # all files
      type: drafts
    values:
      layout: post
      author: AlfredoRamos
      permalink: /:title
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      author: AlfredoRamos
      permalink: /:title
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
      author: AlfredoRamos

# Build settings
markdown: kramdown
theme: minima
encoding: 'utf-8'
paginate_path: /page-:num
paginate: 10
timezone: America/Mexico_City
exclude:
  - LICENSE
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
sass:
    sass_dir: _scss
    style: compressed
gems:
  - jekyll-paginate
  - jekyll-github-metadata


# Needed to build locally
# https://help.github.com/articles/repository-metadata-on-github-pages/
repository: AlfredoRamos/AlfredoRamos.github.io
