# Site settings
title: 'Alfredo Ramos'
description: null
baseurl: null # the subpath of your site, e.g. /blog/
url: null # the base hostname & protocol for your site

# Default settings
defaults:
  -
    scope:
      path: '' # all files
      type: drafts
    values:
      layout: post
      author: AlfredoRamos
      permalink: /:title
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      author: AlfredoRamos
      permalink: /:title
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
      author: AlfredoRamos

# Build settings
theme: minima
encoding: 'utf-8'
paginate_path: /page-:num
paginate: 10
timezone: America/Mexico_City
exclude:
  - LICENSE
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
kramdown:
    input: GFM
    hard_wrap: false
sass:
    sass_dir: _scss
    style: compressed
plugins:
  - jekyll-paginate
  - jekyll-github-metadata

verifications:
    google: 'sgG6KmCJADN3NqJaCyaVjnhYBciwR2LM2uz8rgdGTJU'

# Needed to build locally
# https://help.github.com/articles/repository-metadata-on-github-pages/
repository: AlfredoRamos/AlfredoRamos.github.io
