# Site settings
title: 'Alfredo Ramos'
description: null
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://alfredoramos.mx' # the base hostname & protocol for your site

# Default settings
defaults:
  -
    scope:
      path: '' # all files
      type: drafts
    values:
      layout: post
      author: AlfredoRamos
      permalink: /:title
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      author: AlfredoRamos
      permalink: /:title
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
      author: AlfredoRamos

# Build settings
theme: null
encoding: 'utf-8'
paginate_path: /page-:num
paginate: 12
timezone: America/Mexico_City
exclude:
  - dist/
  - CNAME
  - LICENSE
  - Rakefile
  - README.md
  - composer.json
  - composer.lock
  - satis.json
  - vendor
  - Gemfile
  - Gemfile.lock
kramdown:
    input: GFM
    hard_wrap: false
sass:
    sass_dir: _scss
    style: compressed
plugins:
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-sitemap
  - jemoji
excerpt_separator: <!-- more -->

verifications:
    google: 'sgG6KmCJADN3NqJaCyaVjnhYBciwR2LM2uz8rgdGTJU'
    yandex: '9342b30f7f9146b5'

word_per_minute: 180 # WPM
image_view_time: 3   # Seconds

# Needed to build locally
# https://help.github.com/articles/repository-metadata-on-github-pages/
repository: AlfredoRamos/AlfredoRamos.github.io
