# Site settings
title: 'Alfredo Ramos'
description: null
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'https://alfredoramos.mx' # the base hostname & protocol for your site

# Default settings
defaults:
  -
    scope:
      path: '' # all files
      type: drafts
    values:
      layout: post
      author: AlfredoRamos
      permalink: /:title
      is_draft: true
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      author: AlfredoRamos
      permalink: /:title
      is_post: true
  -
    scope:
      path: ''
      type: pages
    values:
      layout: page
      author: AlfredoRamos
      is_page: true

# Build settings
theme: null
encoding: 'utf-8'
excerpt_separator: <!-- more -->
timezone: America/Mexico_City
exclude:
  - dist/
  - CNAME
  - LICENSE
  - Rakefile
  - README.md
  - composer.json
  - composer.lock
  - satis.json
  - vendor
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-target-blank
kramdown:
    input: GFM
    hard_wrap: false
sass:
    sass_dir: _scss
    style: compressed
repository: AlfredoRamos/AlfredoRamos.github.io
pagination:
  enabled: true
  title: ':title'
  per_page: 12
  permalink: '/page/:num/'
  sort_reverse: true
target-blank:
    rel: external
word_per_minute: 180
image_view_time: 3 # Seconds
