baseURL: 'https://alfredoramos.mx/'
defaultContentLanguage: 'en'
languageCode: 'en'
title: 'Alfredo Ramos'
languages:
  en:
    languageName: English
    weight: 1
  es:
    languageName: Español
    taxonomies:
      categoria: categorias
      etiqueta: etiquetas
      archivo: archivos
    params:
      tagline: 'Una colección de proyectos personales'
      biography: 'Soy ingeniero en sistemas computacionales, entusiasta del software de código libre, apasionado de Arch Linux y GNU/Linux en general.'
      flag: 'twemoji:flag-for-flag-mexico'
    weight: 2
params:
  tagline: 'A collection of personal projects'
  biography: 'I am a computer systems engineer, open source software enthusiast, passionate about Arch Linux and GNU/Linux in general.'
  author: 'AlfredoRamos'
  flag: 'twemoji:flag-for-flag-united-states'
taxonomies:
  category: categories
  tag: tags
  archive: archives
removePathAccents: true
permalinks:
  posts: '/:slug/'
  pages: '/:slug/'
mediaTypes:
  application/atom+xml:
    suffixes: ['atom']
outputFormats:
  ATOM:
    mediatype: application/atom+xml
outputs:
  home: ['HTML', 'ATOM']
  page: ['HTML']
  section: ['HTML', 'ATOM']
  taxonomy: ['HTML', 'ATOM']
  term: ['HTML', 'ATOM']
paginate: 12
markup:
  highlight:
    anchorLineNos: true
    lineNos: true
pygmentsUseClasses: true
disableHugoGeneratorInject: true
disableKinds: ['section']
enableRobotsTXT: true
minify:
  minifyOutput: false
related:
  includeNewer: true
  indices:
  - name: keywords
    weight: 100
  - name: tags
    weight: 80
  - name: categories
    weight: 60
  - name: date
    weight: 10
  threshold: 80
  toLower: true
