baseURL: 'https://alfredoramos.mx/'
languageCode: 'en-US'
title: 'Alfredo Ramos'
params:
  tagline: 'A collection of personal projects'
  biography: 'I am a computer systems engineer, open source software enthusiast, passionate about Arch Linux and GNU/Linux in general.'
  author: 'AlfredoRamos'
taxonomies:
  category: categories
  tag: tags
  archive: archives
permalinks:
  posts: '/:title/'
  pages: '/:title/'
mediaTypes:
  application/atom+xml:
    suffixes: ['atom']
outputFormats:
  ATOM:
    mediatype: application/atom+xml
outputs:
  home: ['HTML', 'ATOM']
  page: ['HTML']
  section: ['HTML', 'ATOM']
  taxonomy: ['HTML', 'ATOM']
  term: ['HTML', 'ATOM']
paginate: 12
markup:
  highlight:
    anchorLineNos: true
    lineNos: true
pygmentsUseClasses: true
disableHugoGeneratorInject: true
disableKinds: ['section']
enableRobotsTXT: true
minify:
  minifyOutput: false
related:
  includeNewer: true
  indices:
  - name: keywords
    weight: 100
  - name: tags
    weight: 80
  - name: categories
    weight: 60
  - name: date
    weight: 10
  threshold: 80
  toLower: true
