baseURL: 'https://alfredoramos.mx/'
languageCode: 'en-US'
title: 'Alfredo Ramos'
params:
  tagline: 'A collection of personal projects'
permalinks:
  posts: '/:title/'
  pages: '/:title/'
paginate: 5
markup:
  highlight:
    anchorLineNos: true
    lineNos: true
pygmentsUseClasses: true
disableKinds:
  - 'section'

# theme
#params:
#  custom_css:
#    - 'css/syntax.css'
