name: GitHub Actions CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          echo "gem: --no-document" > ~/.gemrc
          gem install -N bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle clean
          gem cleanup
      - name: Test SCSS
        run: bundle exec rake scss_lint
      - name: Test Ruby
        run: bundle exec rake rubocop
      - name: Test Jekyll
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
        run: bundle exec jekyll doctor --trace
  deploy:
    if: ${{ !contains(github.event.head_commit.message, '[skip cd]') && github.event_name == 'push' && success() }}
    name: CD
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          echo "gem: --no-document" > ~/.gemrc
          gem install -N bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle clean
          gem cleanup
      - name: Build site
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
        run: bundle exec jekyll build --strict_front_matter --verbose --trace
      - name: Deploy site
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: 'gh-pages'
          cname: alfredoramos.mx
          force_orphan: true
      - name: Clear CloudFlare cache
        if: ${{ !contains(github.event.head_commit.message, '[skip cache]') && success() }}
        env:
          CLOUDFLARE_API_ZONE_ID: ${{ secrets.CLOUDFLARE_API_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: bundle exec cache:clear
