name: GitHub Actions CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  schedule:
    - cron: '0 0 1 * *' # Every month (first day at 00:00)

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && github.event_name != 'schedule'}}
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          echo "gem: --no-document" > ~/.gemrc
          gem install -N bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle clean
          gem cleanup
      - name: Test SCSS
        run: bundle exec rake scss_lint
      - name: Test Ruby
        run: bundle exec rake rubocop
      - name: Test Jekyll
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
        run: bundle exec jekyll doctor --trace

  deploy:
    if: ${{ !contains(github.event.head_commit.message, '[skip cd]') && github.event_name == 'push' && success() }}
    name: CD
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          echo "gem: --no-document" > ~/.gemrc
          gem install -N bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle clean
          gem cleanup
      - name: Build site
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
        run: bundle exec jekyll build --strict_front_matter --verbose --trace
      - name: Deploy site
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: 'gh-pages'
          cname: alfredoramos.mx
          force_orphan: true
      - name: Clear CloudFlare cache
        if: ${{ !contains(github.event.head_commit.message, '[skip cache]') && success() }}
        env:
          CLOUDFLARE_API_ZONE_ID: ${{ secrets.CLOUDFLARE_API_ZONE_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: bundle exec rake cache:clear

  satis:
    if: ${{ !contains(github.event.head_commit.message, '[skip satis]') && github.event_name == 'schedule' }}
    name: Satis
    runs-on: ubuntu-latest
    env:
      BRANCH: satis
      HUB_PROTOCOL: https
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
      GITHUB_NAME: 'Alfredo Ramos'
      GITHUB_EMAIL: '4165935+AlfredoRamos@users.noreply.github.com'
      GIT_COMMIT_TITLE: 'Update Satis repository'
      GIT_COMMIT_BODY: ':robot: Automated updates for my public phpBB extensions Satis repository.'
    steps:
      - name: Checkout source
        uses: actions/checkout@master
        with:
          ref: master
          token: ${{ env.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: composer:v2
          coverage: none
      - name: Setup environment
        id: setup-env
        run: echo "::set-output name=composer-dir::$(composer config cache-files-dir)"
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.setup-env.outputs.composer-dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock', '**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Load SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SATIS_SSH_KEY }}
      - name: Sync ${{ env.BRANCH }} branch
        run: |
          remote_exists=$(git ls-remote --exit-code -h origin ${{ env.BRANCH }} | wc -l)
          local_exists=$(git branch --list satis | wc -l)
          if (( $local_exists > 0 && $remote_exists > 0 ))
          then
            git checkout ${{ env.BRANCH }}
            git merge --ff-only origin/${{ env.BRANCH }}
          elif (( $local_exists == 0 && $remote_exists > 0 ))
          then
            git checkout -b ${{ env.BRANCH }} origin/${{ env.BRANCH }}
          elif (( $local_exists > 0 && $remote_exists == 0 ))
          then
            git branch -qD ${{ env.BRANCH }}
            git checkout -b ${{ env.BRANCH }}
          else
            git checkout -b ${{ env.BRANCH }}
          fi
      - name: Install dependencies
        run: composer update -n --prefer-dist --no-progress
      - name: Update Satis repository
        run: vendor/bin/satis build -n --skip-errors
      - name: Look for changes
        id: git-files
        run: |
          git add .
          git status
          echo "::set-output name=changed::$(git diff --name-only HEAD | wc -l)"
      - name: Commit changes
        id: git-commit
        if: ${{ steps.git-files.outputs.changed > 0 }}
        run: |
          git config --local --replace-all user.name "${{ env.GITHUB_NAME }}"
          git config --local --replace-all user.email "${{ env.GITHUB_EMAIL }}"
          git commit -qam "[${{ env.BRANCH }}] ${{ env.GIT_COMMIT_TITLE }}"
          git push origin -q ${{ env.BRANCH }}
          echo "::set-output name=pr-exists::$(hub pr list -s open -h ${{ env.BRANCH }} | grep '${{ env.GIT_COMMIT_TITLE }}' | wc -l)"
      - name: Send pull request
        if: ${{ steps.git-files.outputs.changed > 0 && steps.git-commit.outputs.pr-exists == 0 }}
        run: |
          pull_msg="$(printf '${{ env.GIT_COMMIT_TITLE }}\n\n${{ env.GIT_COMMIT_BODY }}')"
          hub pull-request -p -b master -h ${{ env.BRANCH }} --no-edit -m "${pull_msg}" -l enhancement,dependencies,satis
